services:
  db:
    image: postgres:17-alpine
    container_name: waveplay-db
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: waveplay
      POSTGRES_PASSWORD: waveplay123
      POSTGRES_DB: waveplay
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waveplay"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: waveplay-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  redisdata:
